spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${db.url}
      username: ${db.username}
      password: ${db.password}

    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${db.url}
      username: ${db.username}
      password: ${db.password}

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

logging.level:
  org.hibernate.SQL: debug
